---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - python-common
enabled: true
ignorePaths:
  - "**/*.egg-info/**"
  - ".tox/**"
  - ".vscode/**"
  - .github/CODEOWNERS
  - .gitignore
  - cspell.config.yaml
