---
name: self-test
on:
  - push
  - pull_request

jobs:
  self-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Self test 'matrix' action
        uses: ./matrix
